// <auto-generated />
using System;
using Lab0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab0.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214204826_Manufacturer-entity")]
    partial class Manufacturerentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Lab0.Data.Entities.ManufacturerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Default Manufacturer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dell"
                        },
                        new
                        {
                            Id = 3,
                            Name = "HP"
                        });
                });

            modelBuilder.Entity("Lab0.Data.Entities.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("production_date");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 2,
                            Created = new DateTime(2025, 12, 14, 21, 48, 25, 557, DateTimeKind.Local).AddTicks(1490),
                            Description = "Business laptop",
                            ManufacturerId = 2,
                            Name = "Laptop",
                            Price = 4500m,
                            ProductionDate = new DateTime(2023, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Category = 2,
                            Created = new DateTime(2025, 12, 14, 21, 48, 25, 570, DateTimeKind.Local).AddTicks(6670),
                            Description = "Laser printer",
                            ManufacturerId = 3,
                            Name = "Printer",
                            Price = 1200m,
                            ProductionDate = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Lab0.Data.Entities.ProductEntity", b =>
                {
                    b.HasOne("Lab0.Data.Entities.ManufacturerEntity", "ManufacturerEntity")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ManufacturerEntity");
                });

            modelBuilder.Entity("Lab0.Data.Entities.ManufacturerEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
